version: 0.0
os: linux
files:
  # 인스턴스에 복사할 S3 파일의 경로, / 로 설정하면 S3_BUCKET_NAME/PROJECT_NAME/GITHUB_SHA.zip을 가져옵니다.
  - source: /
    # S3에서 가져온 파일을 저장할 위치
    destination: /home/ubuntu/dm2023-nest-app
    # 덮어쓰기 옵션
    overwrite: yes

# files에서 가져온 파일들에게 권한을 어떻게 적용해야하는지 지정하는 곳입니다.
permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before_deploy.sh
      runas: ubuntu
  AfterInstall: # LifeCycle Event Hook의 이름을 의미합니다.
    - location: scripts/after_deploy.sh # 스크립트의 위치입니다. files.destination에 정의한 경로에 대한 상대경로롤 작성해주세요.
      timeout: 600 # 스크립트 실행시, 여기에 지정된 시간을 초과하면 안됩니다. 최대 3600초입니다.
      runas: ubuntu # 스크립트 실행 시 가장하는 사용자입니다.