version: 0.0
os: linux
files:
  # 인스턴스에 복사할 S3 파일의 경로, / 로 설정하면 S3_BUCKET_NAME/PROJECT_NAME/GITHUB_SHA.zip을 가져옵니다.
  - source: /
    # S3에서 가져온 파일을 저장할 위치
    destination: /home/ubuntu/dm2023-nest-app
    # 덮어쓰기 옵션
    overwrite: yes

# files에서 가져온 파일들에게 권한을 어떻게 적용해야하는지 지정하는 곳입니다.
permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu