version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: proxy
    network_mode: "host"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: "always"