version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
    # nginx 설장 파일 volume 맵핑
    volumes:
      - ./nginx/dm2023-nest.conf:/etc/nginx/nginx.conf
    restart: "always"

  dm2023-nest:
    build:
      # 빌드할 Dockerfile 경로
      context: ./
    container_name: dm2023-nest
    restart: always
    expose:
      - "3000"