version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./dm2023-nest.conf:/etc/nginx/conf.d/

  dm2023-nest:
    build:
      context: ./
    container_name: dm2023-nest
    restart: always
    expose:
      - "3000"