version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    # nginx 설장 파일 volume 맵핑
    volumes:
      - ./dm2023-nest.conf:/etc/nginx/conf.d/
    # 내부에서 에러로 인해 container가 죽을 경우 restart
    restart: "unless-stopped"

  dm2023-nest:
    build:
      # 빌드할 Dockerfile 경로
      context: ./
    container_name: dm2023-nest
    restart: always
    expose:
      - "3000"