name: Deploy NestJs Application

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # 현재 레포지토리로 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v3

        # NodeJS을 설치
      - name: Setup Node.js 18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'

      # Dependency들을 설치
      - name: Install Dependencies
        run: npm install

      # env 파일을 생성
      - name: Create .env file
        run: |
          jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      # NestJS Application을 빌드
      - name: Build a Nest Application
        run: npm run build
        shell: bash

      # 레포지토리를 압축시킵니다. 불필요한 node_module, coverage, src, test, readme, .git* 등의 파일은 제외
      - name: Make a zip file
        run: zip -r ./$GITHUB_SHA.zip . -x "node_modules/*" "coverage/*" "src/*" "test/*" "README.md" "*.git*"
        shell: bash

      # AWS 자격 증명
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $REGION

      # S3 업데이트
      - name: Upload to S3
        run: aws s3 cp --region $REGION ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      # CodeDeploy에게 배포 요청
      - name: Request Deployment
        run: aws deploy create-deployment --application-name $AWS_CODEDEPLOY_APPLICATION_NAME --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name $AWS_CODEDEPLOY_DEPLOYMENT_GROUP_NAME --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip