name: Deploy NestJs Application

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@2.4.2

      - name: Setup Node.js 18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Create .env file
        run: |
          jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: Build a Nest Application
        run: npm run build
        shell: bash

      - name: Make a zip file
        run: zip -r ./$GITHUB_SHA.zip . -x "node_modules/*" "coverage/*" "src/*" "test/*" "README.md" "*.git*"
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $REGION

      - name: Upload to S3
        run: aws s3 cp --region $REGION ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Request Deployment
        run: aws deploy create-deployment --application-name $AWS_CODEDEPLOY_APPLICATION_NAME --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name $AWS_CODEDEPLOY_DEPLOYMENT_GROUP_NAME --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip

env:
  REGION: ap-northeast-2
  # S3 버킷 이름
  S3_BUCKET_NAME: dm2023-bucket
  # S3 버킷 내 폴더 이름
  PROJECT_NAME: dm2023_nest
  # CodeDeploy 애플리케이션 이름
  AWS_CODEDEPLOY_APPLICATION_NAME: NestJS-App-Codedeploy
  # CodeDeploy 배포 그룹 이름
  AWS_CODEDEPLOY_DEPLOYMENT_GROUP_NAME: NestJS-DG