name: Deploy NestJs Application

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Checkout Repository'
      - name: Checkout Repository
        uses: actions/checkout@2.4.2
        
          
